name: Hello

on:
    push:
        branches:
            - main
job:
    say_hello:
        runs-on: ubuntu-latest
        steps:
            -name: Print a greeting
            run: echo "Hello World!"