name: Hello

on:
    push:
        branches:
            - main
    workflow_dispatch: {}

concurrency:
    group: main-deploy
    cancel-in-progress: true
job:
    say_hello:
        runs-on: ubuntu-latest
        steps:
            -name: Print a greeting
            run: echo "Hello World!"